import Head from 'next/head'
import { useRouter } from 'next/router';

function AdditionLobby() {
  const router = useRouter();
  const { username, gameType } = router.query

  console.log('in addition Lobby ', username)
  console.log('in addition Lobby ', gameType)


  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome, {username}</h1>
        <p>{gameType}</p>
        <section>

        </section>
      </main>
    </div>
  )
}

export default AdditionLobby;
