import Head from 'next/head'
import MultiplicationLobby from './multiplicationLobby';
import { useRouter } from 'next/router';

function DivisionLobby() {
  const router = useRouter();
  const { username, gameType } = router.query

  console.log('in division Lobby ', username)
  console.log('in division Lobby ', gameType)


  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MultiplicationLobby />
    </div>
  )
}

export default DivisionLobby;
