import Head from 'next/head'
import AdditionLobby from './additionLobby';

function SubtractionLobby() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AdditionLobby />
      </main>
    </div>
  )
}

export default SubtractionLobby;
