import Head from 'next/head'
import AdditionLobby from './additionLobby';

function SubtractionLobby() {
  return (
    <div >
      <Head>
        <title>Mission Room</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <AdditionLobby />
      </main>
    </div>
  )
}

export default SubtractionLobby;
